== 식당 API

=== 식당 정보 등록

operation::store-info-controller-test/create_store-info_success[snippets="http-request,http-response"]

=== 식당 정보 조회

operation::store-info-controller-test/find_store_success[snippets="http-request,http-response"]

=== 식당 정보 수정

operation::store-info-controller-test/update_store-info_success[snippets="http-request,http-response"]

=== 식당 계정 생성

operation::store-controller-test/create_store_success[snippets="http-request,http-response"]

=== 식당 계정 삭제

operation::store-controller-test/delete_store_success[snippets="http-request,http-response"]

=== 식당 로그인

operation::store-auth-controller-test/company_auth_success[snippets="http-request,http-response"]

=== 식당 로그아웃

operation::store-auth-controller-test/company_logout_success[snippets="http-request,http-response"]

=== 식당 계좌 등록

operation::store-account-controller-test/create_store-account_success[snippets="http-request,http-response"]

=== 메뉴 등록

operation::menu-controller-test/create_menu_success[snippets="http-request,http-response"]

=== 메뉴 단건 조회

operation::menu-controller-test/find-one_menu_success[snippets="http-request,http-response"]

=== 메뉴 목록 조회

operation::menu-controller-test/find-all_menu_success[snippets="http-request,http-response"]

=== 메뉴 수정

operation::menu-controller-test/modify_menu_success[snippets="http-request,http-response"]

=== 메뉴 삭제

operation::menu-controller-test/delete_menu_success[snippets="http-request,http-response"]

=== 판매 기록 생성

operation::sales-controller-test/create_sales_success[snippets="http-request,http-response"]