### 기업 로그인
POST localhost:8080/companies/auth
Content-Type: application/json

{
  "email": "company1@ssafy.com",
  "password": "12345678"
}

### 대시보드1
GET  localhost:8080/companies/dashboards/years/months?startDate=2024-10-04T00:00:00&endDate=2024-10-06T23:23:59

### 대시보드2
GET  localhost:8080/companies/dashboards/months/departments?startDate=2024-10-06T00:00:00&endDate=2024-10-06T23:23:59

### 대시보드3
GET  localhost:8080/companies/dashboards/months/employees?startDate=2024-10-06T00:00:00&endDate=2024-10-06T23:23:59

### 대시보드4
GET  localhost:8080/companies/dashboards/months/stores?startDate=2024-10-06T00:00:00&endDate=2024-10-06T23:23:59